services:
  templateapi:
    build:
      context: .
      dockerfile: TemplateAPI/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Add other services if needed
  # otherapi:
  #   build:
  #     context: .
  #     dockerfile: MyOtherAPI/Dockerfile
  #   ports:
  #     - "7001:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  postgresdb:
    image: "postgres:13"
    environment:
      POSTGRES_DB: MyDB
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
